Refactoring of KDIC MainActivity.java
GrinnellAppDev/KDIC-Radio-Android pull request #39
Opened 2017-03-14 02:15 UTC by nikagarwal98

* Added member variables in onDestroy
* Made all member variables private
* Cleaned up setupPlaybackToolbar()

2017-03-14 05:29 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        super.onDestroy();
Why is this called twice? Also you want to do your clean up before you call `super.onDestroy()`

2017-03-14 05:29 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>          Log.d(TAG, "MainActivity Destroyed.");
Logs shouldn't be in production code.

2017-03-14 05:30 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>              AlphaAnimation alphaAnimation = new AlphaAnimation(1f, 0f);
What is 1f? A magic number ? Please help us make more meaning of these by extracting them as constants and naming them properly.

2017-03-14 05:30 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +            final float shiftAmnt = (mPlaybackToolbar.getWidth() - mPlayPauseButton.getWidth()) / 2;
Why are we dividing by some random magic number? What is 2 here? Extract as a constant and name properly

2017-03-14 05:31 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>              animation.setDuration(200);
Magic number. You know what to do

2017-03-14 05:31 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>              TranslateAnimation animation = new TranslateAnimation(shiftAmnt, 0, 0, 0);
0's here do not make sense to anyone reading the code. You might want to extract these as constants and give them descriptive names.

2017-03-14 05:32 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>              animation.setDuration(200);
A proper extraction would be `private static final int MS_ANIMATION_DURATION;` (notice the naming convention -- using MS (representing millisecond) to tell the reader that it is time in milliseconds.

2017-03-14 05:33 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                                  if (mBackStack.peek() != R.id.visualizer)
Too many unclear numbers here. Extract as constants. See comments below

2017-03-14 05:33 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +    private View.OnClickListener togglePlayPauseClickListener() {
This method is too long. Modularize it.

2017-03-14 05:34 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>          // bind to the radio service
No need for this comment

2017-03-14 05:34 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>          // set the layout to use
Remove this comment

2017-03-14 05:34 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>          setupNavigation(); // setup the nav drawer and navigation functionality
Remove these inline comments as well. Use inline comments when you're doing something that absolutely requires explanation

2017-03-14 05:35 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                      if (NetworkState.isOnline(MainActivity.this)) {
Use a static import of this method to make it shorter

2017-03-14 05:36 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                                              Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF,
Use static imports. Also, handle these strange numbers appropriately by extracting them into meaningfully-named constants. eg. I have no idea what 360 or 0.5f means in this context.

2017-03-14 05:36 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +                                    float shiftX = mPlaybackToolbar.getWidth() / -2 + mPlayPauseButton.getWidth();
See comments about numbers above

2017-03-14 05:37 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                                  rotate.setRepeatCount(Animation.INFINITE);
Use static imports

2017-03-14 05:37 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        // set up mBackStack
No need for this comment

2017-03-14 05:38 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                  mDrawerLayout.closeDrawer(GravityCompat.START);
Use static import

2017-03-14 05:39 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
Document the class using Javadoc style 
See: https://www.tutorialspoint.com/java/java_documentation.htm

2017-03-14 05:39 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>              Log.e(TAG, "onServiceDisconnected");
Logs should be removed

2017-03-14 05:39 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>          Log.d(TAG, "onStart");
Remove logs

2017-03-14 05:46 UTC, LarryAsante requested changes
Nice start. There are more changes to be done so lets focus on those so we can iterate from there.

2017-04-13 02:37 UTC, mattorib requested changes

2017-04-13 02:37 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        // different center point for rotation if mPlayPauseButton is in the
Remove these comments

2017-04-13 02:37 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                  // close the drawer after something is clicked
Remove comment

2017-04-13 23:52 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>      protected void onCreate(Bundle savedInstanceState) {
Nice! Now, our `onCreate(...)` looks much better!

2017-04-13 23:54 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        super.onDestroy();
Good call!

2017-04-13 23:57 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>          mBackStack = new Stack<>();
Aha! So you're initializing `mBackStack` here, which is good. But you never free it after use for recycling. You should nullify it in `onDestroy()` else you're likely to leak some memory

2017-04-14 00:00 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        super.onDestroy();
Also: Why are you nullifying only `mFavoritesFragment` and not the others? You should do it for the others!

2017-04-14 00:01 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        mFavoritesFragment = null;
Aight. Sike! You got me on this one! Good job. See my other comments!

2017-04-14 00:02 UTC, LarryAsante requested changes
Very nice! See my other comments!

2017-04-16 18:24 UTC, closed without merging