Refactor Main Activity
GrinnellAppDev/KDIC-Radio-Android pull request #42
Opened 2017-03-29 05:07 UTC by linhpha

2017-03-30 21:03 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +    //Set the tag for Main Activity class
You should remove this in-line comment. It's pretty obvious from the code.

2017-03-30 21:04 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +    /**
Do not comment inherited methods. **Only** comment methods you write

2017-03-30 21:04 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        // setup the nav drawer and navigation functionality
This method is obvious from the method name. You don't have to comment it.

2017-03-30 21:05 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +     *Bind the radio services after the activity is being displayed to the user
Let's remove this comment

2017-03-30 21:05 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        // Start an intent to bind to the radio service
We should remove this as well

2017-03-30 21:06 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +     *Set up icon for the pause and play button
Remove this comment

2017-03-30 21:06 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +     * Stop the activity
Remove this as well

2017-03-30 21:23 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>      private void setupPlaybackToolbar() {
I like that you comment this method. This method is supposed to set the Bottom navigation. let's keep it at exactly that. It's very long and we need to break it into smaller chunks. We can separate all of the onClick listeners into a `setButtomNavigationOnClickListeners()` and that'll cut it down.

2017-03-30 21:23 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>      private void setupNavigation() {
This method is too long.

2017-03-30 21:24 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>      public void showVisualizeFragment() {
Let's shorten this method too

2017-03-30 21:25 UTC, LarryAsante requested changes
Nice work on this, Linh. There's some more work to be done on this:
* Let's break long methods to smaller methods
* Use static imports where necessary
* Remove in-line comments in which the code is obvious

2017-04-05 18:39 UTC, linhpha commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        // setup the nav drawer and navigation functionality
@LarryAsante I changed and commited a new change in this pull request. Can you take a look at it? Thank you!

2017-04-06 01:03 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +                    ft.replace(R.id.fragment, new BlogWebViewFragment(), BlogWebViewFragment.TAG)
Use a static import for the `TAG` here to shorten the code.

2017-04-06 01:03 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +                    //Generate blog fragment in response to the blog button
Remove this inline comment. I don't think it is necessary

2017-04-06 01:11 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +                setBottomNavigationOnClickListeners(v);
I think the right method name for this, will be `toggleVisualizeFragmentOnClick(...)`

2017-04-06 01:12 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +    public void setBottomNavigationOnClickListeners(View v) {
This doesn't really define what the function does. This toggles the Visualization Fragment so it should be named `toggleVisualizationFragment(..)` or `toggleVisualizationFragmentOnClick(..)`

2017-04-06 01:15 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +     * Set response when clicking in the bottom navigation
This isn't too descriptive. It should tell us what happens on clicking the BottomBar (i.e Shows/hide the visualization fragment (replace this with : {@link [name of the visualization fragment] on click)

2017-04-06 01:15 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +    public void setBottomNavigationOnClickListeners(View v) {
Are you using this method elsewhere? if no, please make this `private`

2017-04-06 01:16 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +            //Create fragment transaction to handle response to call from the navigation drawer
Remove comment

2017-04-06 01:16 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        mDrawerLayout.closeDrawer(GravityCompat.START);
Use static import here

2017-04-06 01:17 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +            moveInfo(0f, 1f);
You should extract these numbers as constants and give them descriptive names

2017-04-06 01:18 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        animation.setDuration(200);
You should extract this number as a constant and give it a descriptive name. eg. `private final int MS_ANIMATION_DURATION = 200;`

2017-04-06 01:19 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        TranslateAnimation animation = new TranslateAnimation(shiftAmnt, 0, 0, 0);
What are these 0's here? I don't know what they are and forcing your client to always read documentation to understand random variables in a function isn't good for readability. Extract them as constants and give them proper naming. You might find it helpful to check the documentation of the constructor to see what those numbers are so you can name the constant properly

2017-04-06 01:19 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        alphaAnimation.setDuration(300);
Extract number as constant

2017-04-06 01:20 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +        alphaAnimation.setStartOffset(100);
Same here. You can extract this as: `private final int MS_ANIMATION_START_OFFSET = 100;` I used the `MS` prefix here to indicate that it is in milliseconds. If it not, change it accordingly.

2017-04-06 01:21 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +            moveInfo(1f, 0f);
Extract method parameters as constants

2017-04-06 01:22 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>      public void updateNavigationView() {
Should this method be public? If you're using it in just this class, you **should** make it `private`

2017-04-06 01:22 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +    public void movePlayButton(float shiftAmnt) {
Also check the access modifier. Should it be `public` or `private`?

2017-04-06 01:23 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +    public void moveInfo(float fromAlpha, float toAlpha) {
Check access modifier

2017-04-06 01:24 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
> +
This line is unnecessary. Remove it. You should format your code before pushing. To use our agreed code style, please see this (https://github.com/square/java-code-styles), install, set-up (select SquareAndroid in the preferred style) and format all of the classes you modify after you set it up

2017-04-06 01:25 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>      public static final String TAG = MainActivity.class.getSimpleName();
Should this tag be public? if you're not using it through out the app, it should stay private

2017-04-06 01:26 UTC, LarryAsante requested changes
Nice work @linhpha. I left a few comments. Please check them and make the necessary corrections/changes.

2017-04-13 23:34 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                              rotate = new RotateAnimation(0, 360, shiftX, shiftY);
Whoops! Looks like you missed this.

2017-04-13 23:37 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>              if (sharedPreferences.getBoolean(Constants.FIRST_RUN, true)) {
Use a static import here

2017-04-16 18:52 UTC, linhpha commented on app/src/main/java/edu/grinnell/kdic/MainActivity.java
>                              rotate = new RotateAnimation(0, 360, shiftX, shiftY);
@LarryAsante  I pushed again

2017-04-16 18:54 UTC, LarryAsante commented
@linhpha There's a conflict but hold on a second. @nikagarwal98 made changes to main. I'll check and merge that so you can pull and make changes to `RadioService.java`

2017-04-16 19:50 UTC, closed without merging