Completed Refactor
GrinnellAppDev/KDIC-Radio-Android pull request #43
Opened 2017-04-06 15:43 UTC by papakoj

2017-04-06 23:46 UTC, LarryAsante approved these changes
Looks good to me. Remove the inline comments in a different PR.

2017-04-06 23:49 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>          if (intent != null && intent.getAction() != null) {
Let's keep `onCreate(..)` short. Extract all of this into some other method and call it in `onCreate(...)`

2017-04-06 23:49 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>                          // Lost focus for an unbounded amount of time: stop playback and release media player
Remove all of the inline comments

2017-04-06 23:50 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>                          // Lost focus for a short time, but it's ok to keep playing
Remove comment

2017-04-06 23:51 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>      public void play() {
Should this method be `public`? Check if it is called elsewhere, else change it to `private`

2017-04-06 23:51 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>          String title = currentShow != null ? currentShow.getTitle() : "Auto Play";
Extract the string into the strings.xml file

2017-04-06 23:53 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
You should also null-ify the `Timer` and the `Runnable` here.

2017-04-06 23:56 UTC, LarryAsante requested changes
Good start. See the comments and make the changes.

2017-04-07 00:11 UTC, mattorib requested changes

2017-04-07 00:11 UTC, mattorib commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>                  .createWifiLock(WifiManager.WIFI_MODE_FULL, "myWifiLock");
Abstract the tag `myWifiLock` out to a constant value (such as a `private static final String WIFI_TAG`)

2017-04-07 00:11 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>              timer.cancel(); // cancel the stop timer if it is loaded
These lines are self-explanatory, so the inline comments are just visual clutter.

2017-04-07 00:11 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>      public void pause() {
Should this be public?

2017-04-07 00:11 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
>              mediaPlayer.start(); // play
Should the media player play if it can't get audio focus?

2017-04-07 00:11 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
Clean up this extra whitespace.

2017-04-07 00:13 UTC, PsychicNoodles commented
Annoyingly I can't comment on things you haven't made changes to, but the `NotificationCompat.Builder` call [here](https://github.com/GrinnellAppDev/KDIC-Radio-Android/pull/43/files/63975c45a4d64022b8841c1c1893d4613df02c61#diff-9c8408614b86c8910680e87f0dfd9174R330) has some embedded strings that should be extracted to the `res/strings.xml` file.

2017-04-13 23:51 UTC, LarryAsante commented
@papakoj See comments above and make the changes

2017-04-16 19:41 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +        // obtain WifiLock
Remove this

2017-04-16 19:41 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +        // time change?? show change
Remove this as well

2017-04-16 19:42 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +                        stopForeground(false); // stop making it a foreground service but leave the notification there
Remove this

2017-04-16 19:42 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +                        // Lost focus for an unbounded amount of time: stop playback and release media player
Remove this

2017-04-16 19:43 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +                        mediaPlayer.setVolume(1.0f, 1.0f);
Extract these numbers as constants.

2017-04-16 19:43 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +        } else { // mediaplayer == null
Unneccessary

2017-04-16 19:44 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +                PendingIntent.FLAG_ONE_SHOT
Static import

2017-04-16 19:45 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/kdic/RadioService.java
> +                0,
Use proper constant

2017-04-16 19:46 UTC, LarryAsante requested changes
Good start, @papakoj ! Fix the comments I post there

2017-04-30 18:30 UTC, LarryAsante approved these changes
Looks good to me

2017-04-30 18:31 UTC, merged